version: 0.2

env:
  variables:
    VITE_URL: "/todo_frontend/VITE_URL"
    DISTRIBUTION_ID: "EH1XNDF4M438Y"
    S3_BUCKET: "test-bucket123-gokul"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing bun ...
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"

  pre_build:
    commands:
      - echo Installing Packages
      - cd frontend
      - bun install
      - echo Running tests with Bun ...
      - bun test
      - echo Tests passed

  build:
    commands:
      - echo Building the Todo app ...
      - bun run build
      - echo Build completed

  post_build:
    commands:
      - echo Deleting old contents from S3 bucket...
      - aws s3 rm s3://$S3_BUCKET/ --recursive
      - echo Uploading new build to S3...
      - pwd
      - ls -la
      - aws s3 cp dist/ s3://$S3_BUCKET/ --recursive
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo Deployment completed.
